import mongoose from "mongoose";
import {
  COMPONENT_TYPE_VALUES,
  INVENTORY_STATUS_VALUES,
  INVENTORY_STATUS,
} from "../constants/inventory.constants.js";

/**
 * Transfer history sub-document.
 * Appended each time a unit is transferred between offices.
 * Provides a full audit trail of the unit's physical movement.
 */
const transferEventSchema = new mongoose.Schema(
  {
    fromOfficeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Office",
      required: true,
    },
    toOfficeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Office",
      required: true,
    },
    transferredAt: {
      type: Date,
      default: Date.now,
    },
    transferredBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    remarks: {
      type: String,
      trim: true,
    },
  },
  { _id: true }
);

/**
 * InventoryUnit — the primary blood unit tracking record.
 *
 * Lifecycle:
 *   Auto-created by the donation completion transaction →
 *   AVAILABLE → RESERVED / ISSUED / TRANSFERRED / EXPIRED / DISCARDED
 *
 * This model supersedes the simpler BloodInventory model from the donation
 * module for full lifecycle management. Records from the donation module's
 * simple BloodInventory creation step are now replaced by this comprehensive schema.
 */
const inventoryUnitSchema = new mongoose.Schema(
  {
    /**
     * Human-readable unique identifier for traceability.
     * Format: BU-YYMM-XXXXXXXX
     * Generated by generateBloodUnitId() in inventory.utils.js.
     */
    bloodUnitId: {
      type: String,
      required: [true, "Blood unit ID is required"],
      unique: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    /**
     * Links back to the originating donation.
     * null for manually created inventory records (transferred-in units, etc.)
     */
    donationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Donation",
      default: null,
      index: true,
    },

    donorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Donor",
      required: [true, "Donor reference is required"],
      index: true,
    },

    officeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Office",
      required: [true, "Office reference is required"],
      index: true,
    },

    bloodGroup: {
      type: String,
      required: [true, "Blood group is required"],
      index: true,
    },

    /**
     * The processed blood component type stored in inventory.
     * Distinct from donationType (what the donor gives vs what gets stored).
     */
    componentType: {
      type: String,
      enum: {
        values: COMPONENT_TYPE_VALUES,
        message: "{VALUE} is not a valid component type",
      },
      required: [true, "Component type is required"],
      index: true,
    },

    /**
     * Date when the blood was physically collected.
     */
    collectionDate: {
      type: Date,
      required: [true, "Collection date is required"],
      index: true,
    },

    /**
     * Calculated automatically based on componentType + collectionDate.
     * Units past this date are ineligible for reservation or issuance.
     */
    expiryDate: {
      type: Date,
      required: [true, "Expiry date is required"],
      index: true,
    },

    /**
     * Volume in millilitres.
     */
    volume: {
      type: Number,
      required: [true, "Volume is required"],
      min: [1, "Volume must be positive"],
    },

    status: {
      type: String,
      enum: {
        values: INVENTORY_STATUS_VALUES,
        message: "{VALUE} is not a valid inventory status",
      },
      default: INVENTORY_STATUS.AVAILABLE,
      index: true,
    },

    /**
     * Physical storage information (e.g., "Rack-A Shelf-3 Box-12").
     */
    storageLocation: {
      type: String,
      trim: true,
      default: null,
    },

    /**
     * Storage temperature in Celsius at time of last recording.
     */
    temperature: {
      type: Number,
      default: null,
    },

    /**
     * User ID the unit is currently reserved for.
     * Set when status → RESERVED, cleared when status → AVAILABLE (released).
     */
    reservedFor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    /**
     * Free-text field describing who the unit was issued to.
     * Can reference a hospital name, patient ID, or internal request ID.
     * Set when status → ISSUED.
     */
    issuedTo: {
      type: String,
      trim: true,
      default: null,
    },

    /**
     * Chronological log of all inter-office transfers.
     * Provides full physical movement audit trail.
     */
    transferHistory: {
      type: [transferEventSchema],
      default: [],
    },

    remarks: {
      type: String,
      trim: true,
      default: null,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Creator reference is required"],
      index: true,
    },

    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

// Core matching query: find available blood of a specific type + group
inventoryUnitSchema.index({
  bloodGroup: 1,
  componentType: 1,
  status: 1,
  expiryDate: 1,
});

// Office-level inventory view
inventoryUnitSchema.index({ officeId: 1, status: 1, bloodGroup: 1, componentType: 1 });

// Near-expiry query support
inventoryUnitSchema.index({ status: 1, expiryDate: 1, isActive: 1 });

const InventoryUnit = mongoose.model("InventoryUnit", inventoryUnitSchema);

export default InventoryUnit;
