import mongoose from "mongoose";
import {
  REQUEST_PRIORITY_VALUES,
  REQUEST_STATUS_VALUES,
  REQUEST_STATUS,
  VALID_BLOOD_GROUPS,
  PATIENT_GENDER_VALUES,
} from "../constants/bloodRequest.constants.js";
import { COMPONENT_TYPE_VALUES } from "../../inventory/constants/inventory.constants.js";

const bloodRequestSchema = new mongoose.Schema(
  {
    /**
     * Auto-generated human-readable request identifier.
     * Format: BR-YYYYMMDD-XXXXXXXX
     * Generated by generateRequestNumber() in bloodRequest.utils.js.
     */
    requestNumber: {
      type: String,
      required: [true, "Request number is required"],
      unique: true,
      uppercase: true,
      trim: true,
      index: true,
    },

    // ── Hospital / Medical Context ──────────────────────────────────────────

    hospitalName: {
      type: String,
      required: [true, "Hospital name is required"],
      trim: true,
      index: true,
    },

    hospitalContact: {
      type: String,
      required: [true, "Hospital contact is required"],
      trim: true,
    },

    patientName: {
      type: String,
      required: [true, "Patient name is required"],
      trim: true,
      index: true,
    },

    patientAge: {
      type: Number,
      required: [true, "Patient age is required"],
      min: [0, "Patient age must be non-negative"],
      max: [150, "Patient age must be realistic"],
    },

    patientGender: {
      type: String,
      enum: {
        values: PATIENT_GENDER_VALUES,
        message: "{VALUE} is not a valid gender",
      },
      required: [true, "Patient gender is required"],
    },

    doctorName: {
      type: String,
      required: [true, "Doctor name is required"],
      trim: true,
      index: true,
    },

    // ── Blood Requirement ─────────────────────────────────────────────────

    bloodGroup: {
      type: String,
      required: [true, "Blood group is required"],
      enum: {
        values: VALID_BLOOD_GROUPS,
        message: "{VALUE} is not a valid blood group",
      },
      index: true,
    },

    componentType: {
      type: String,
      required: [true, "Component type is required"],
      enum: {
        values: COMPONENT_TYPE_VALUES,
        message: "{VALUE} is not a valid component type",
      },
      index: true,
    },

    unitsRequested: {
      type: Number,
      required: [true, "Units requested is required"],
      min: [1, "At least 1 unit must be requested"],
    },

    priority: {
      type: String,
      required: [true, "Priority is required"],
      enum: {
        values: REQUEST_PRIORITY_VALUES,
        message: "{VALUE} is not a valid priority level",
      },
      default: REQUEST_STATUS.PENDING,
      index: true,
    },

    reason: {
      type: String,
      required: [true, "Medical reason / diagnosis is required"],
      trim: true,
    },

    /**
     * Deadline by which the blood must be delivered.
     * Drives priority escalation and SLA tracking.
     */
    requiredBefore: {
      type: Date,
      required: [true, "Required before date is required"],
      index: true,
    },

    // ── Office Assignment ─────────────────────────────────────────────────

    officeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Office",
      required: [true, "Office reference is required"],
      index: true,
    },

    // ── Status & Lifecycle ────────────────────────────────────────────────

    status: {
      type: String,
      required: true,
      enum: {
        values: REQUEST_STATUS_VALUES,
        message: "{VALUE} is not a valid request status",
      },
      default: REQUEST_STATUS.PENDING,
      index: true,
    },

    /**
     * Array of InventoryUnit ObjectIds allocated to fulfill this request.
     * Built up incrementally during partial and full allocations.
     * Allows audit of exactly which blood units were used.
     */
    allocatedUnits: {
      type: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "InventoryUnit",
        },
      ],
      default: [],
    },

    fulfilledAt: {
      type: Date,
      default: null,
    },

    remarks: {
      type: String,
      trim: true,
      default: null,
    },

    /**
     * The person (STAFF/external contact) on whose behalf the request is made.
     * Typically set to req.user._id on creation.
     */
    requestedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Requester reference is required"],
      index: true,
    },

    /**
     * ADMIN or SUPER_ADMIN who approved the request.
     * Set when status transitions to APPROVED.
     */
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    /**
     * Authenticated user who created the record (audit field).
     */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Creator reference is required"],
    },

    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

// Primary listing index (most common query pattern: office + status + priority)
bloodRequestSchema.index({ officeId: 1, status: 1, priority: 1, requiredBefore: 1 });

// Dashboard and reporting index
bloodRequestSchema.index({ status: 1, createdAt: -1 });

// Text search index for hospital/patient/doctor search
bloodRequestSchema.index(
  { requestNumber: "text", hospitalName: "text", patientName: "text", doctorName: "text" },
  { name: "blood_request_text_search" }
);

const BloodRequest = mongoose.model("BloodRequest", bloodRequestSchema);

export default BloodRequest;
